Don't write unrecognized license to source tree.
This is a common issue. We can short circuit it,
rather than modifying Android.bp and having to
wait for the build to fail.

Bug: N/A
Test: update crosvm, see immediate failure. Note: rebuild of ninja file was still needed in
  this case, but I believe it's because of the Cargo.lock file being changed next to an
  Android.bp file there. We can investigate that separately.

```
:) ./android-merge-2-cargo-embargo.sh
...
+ cargo_embargo --cargo-bin .../.rustup/toolchains/1.77.2-x86_64-unknown-linux-gnu/bin generate cargo_embargo.json
WARNING: ignoring test "jail_test_tests_fork" with harness=false. not supported yet
ERROR: Unrecognized license: Apache-2.0 or BSD-3-Clause
```

Change-Id: I636ab87d29bfde9dd29cad813a212e0a6ee22a8d